### ISSUE TITLE
flightradar24 container not starting up / crashing

### ISSUE THREAD

**Issue by itzy77** [ShoGinn/flightradar24#4]
Hi,

first of all: thanks for maintaining these projects, they are pretty much exactly what i am looking for.

I'd like to use dump1090, flightradar24 and flightaware. While flightaware works fine (and therefore I assume dump1090 also works correctly), the log of flightradar24 just shows:
```
...
PING feed.flightradar24.com(2606:4700::6811:2d34 (2606:4700::6811:2d34)) 56 data bytes
--- feed.flightradar24.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
Waiting for dump1090 to start up
eating the base ini file
Server:		192.168.1.2
Address:	192.168.1.2#53
Non-authoritative answer:
Name:	feed.flightradar24.com
Address: 104.17.44.52
Name:	feed.flightradar24.com
Address: 104.17.43.52
Name:	feed.flightradar24.com
Address: 104.17.42.52
Name:	feed.flightradar24.com
Address: 104.17.46.52
Name:	feed.flightradar24.com
Address: 104.17.45.52
PING feed.flightradar24.com(2606:4700::6811:2e34 (2606:4700::6811:2e34)) 56 data bytes
--- feed.flightradar24.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
Waiting for dump1090 to start up
eating the base ini file
Server:		192.168.1.2
Address:	192.168.1.2#53
Non-authoritative answer:
Name:	feed.flightradar24.com
Address: 104.17.46.52
Name:	feed.flightradar24.com
Address: 104.17.45.52
Name:	feed.flightradar24.com
Address: 104.17.44.52
Name:	feed.flightradar24.com
Address: 104.17.43.52
Name:	feed.flightradar24.com
Address: 104.17.42.52
PING feed.flightradar24.com(2606:4700::6811:2a34 (2606:4700::6811:2a34)) 56 data bytes
--- feed.flightradar24.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
Waiting for dump1090 to start up
eating the base ini file
Server:		192.168.1.2
Address:	192.168.1.2#53
```
... and so on ...

Any hints where to look at? It seems the flightradar ping goes wrong, however that's before the actual FR24 banner from the feeder.

Thanks for any ideas.

Kind regards
Christian

**Comment by ShoGinn** [comment]
The DNS it's pulling up for ping is IPv6 and either there is an issue with your WAN ipv6 or flight radar.

This is a known issue.

If you read my code:

https://github.com/ShoGinn/flightradar24/blob/76e6150d20cda207b6461e189486eeab1eb18f09/rootfs/usr/local/bin/docker_entrypoint.sh#L33-L35

https://forum.flightradar24.com/forum/radar-forums/flightradar24-feeding-data-to-flightradar24/11595-problems-with-feeder-statistics-and-data-sharing?11943-Problems-with-feeder-statistics-and-data-sharing=

The link should help you... even though disabling ipv6 is a horrible fix sorry!
